language: node_js

node_js:
  - 6.0.0

branches:
  only:
    - master

before_install:
  - npm install -g hexo
  - npm install -g firebase-tools

install: 
  - npm install

script: hexo generate

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
